### ISSUE TITLE
TAW View Distance: yea or nay?

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/TvT_Dark_Business_Adleredition.altis#19]
http://www.armaholic.com/page.php?id=19751

**Comment by Fusselwurm** [comment]
evtl reicht auch ACE_viewDistance, mit enforced setting auf 5000

**Comment by Fusselwurm** [comment]
atm https://github.com/gruppe-adler/TvT_Dark_Business_Adleredition.altis/blob/altis-se/description.ext#L52 ists auf 5000 . ich könnt noch runtergehn auf 3500 - simmax u.a. arbeiten üblweise mit der VD

**Comment by Fusselwurm** [comment]
hat sich keiner über die VD beschwert beim spielen - ich glaub ich warte bis ace die mk1eyeballs integriert hat, und leg dann 3000 fest oder so :P

**Comment by Salbei2500** [comment]
Omg nur 3000 ich kann zwar im Dunkeln kaum weiter als 2000 sehen. Aber das ist einfach viel zu wenig.

**Comment by Fusselwurm** [comment]
@jackjonsen ich würd die 3000 nicht als max-distance nehmen (wie es jetzt mit den 5000 ist), sondern als Basisdistanz, wo dann die Verlängerung durch Mk1Eyeballs dazukommt. :)

**Comment by Fusselwurm** [comment]
atm festgelegt, ab nächster version ace_viewdistance mit variabler VD :)
