### ISSUE TITLE
Kontrollierbarkeit der Geisel erhöhen

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/TvT_Dark_Business_Adleredition.altis#2]
Mit kleinen IND-Teams ist das Spiel atm fast unmöglich zu gewinnen, die Geisel kann viel zu einfach Mist machen (aus fahrenden Fahrzeugen springen, sich in deren Inventar bedienen etc)

**Comment by nomisum** [comment]
Wäre zu prüfen, ob sie auch aus mit ACE abgeschlossenen Autos springen kann. 

```
[bob, car1, true] call ACE_VehicleLock_fnc_addKeyForVehicle; - will add a ACE_magazine_customKey to bob and program it to work on car1
```

https://github.com/acemod/ACE3/tree/master/addons/vehiclelock

**Comment by nomisum** [comment]
"There are no walking animations with your hands on your back, so a walking captive is impossible."

Da man die BIS Animationen nicht editieren kann (binarisiert), wird man auch nicht bestehende Animationen zu einem "Hands-On-Back" verwursten können. Also zumindest von ACE ist ein gefesseltes Laufen nicht zu erwarten.

**Comment by Fusselwurm** [comment]
```
[13:03:15] <fusselwurm> btw, kann man prüfen ob ein spieler im inventar ist?
[13:03:35] <nomisum> im was? ach so, dass er es offen hat? ja
[13:03:41] <fusselwurm> ich fänd es sinnvoll, spielern in der nähe anzuzeigen wenn die geisel in nem rucksack wühlt oder im auto-inventar
[13:04:00] <nomisum> https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#InventoryOpened 
[13:04:12] <fusselwurm> das wär noch ne realismus-option, die die handlungsoptionen der geisel nicht einschränken würde, und dennoch das flohhüten für IND/OPFOR einfahcre macht
```

**Comment by Fusselwurm** [comment]
players cannot access inventory while in vehicles that do not belong to their side. d9879842923865f8f9db4ec83dc580452fd21824 . 

Should be enough. When player is outside vehicles, you can always see their rummaging in an inventory.

**Comment by Fusselwurm** [comment]
also, message in vehicle chat if hostage jumps out of moving vehicle thats not BLUFOR

**Comment by Fusselwurm** [comment]
maybe d987984 could be further improved using new info from https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#InventoryOpened

**Comment by Fusselwurm** [comment]
> also, message in vehicle chat if hostage jumps out of moving vehicle thats not BLUFOR

doesnt work.

*edit: fixed with c09cbc355818b8c5f32964628a60672086fca955*

**Comment by Fusselwurm** [comment]
> players cannot access inventory while in vehicles that do not belong to their side. d987984 .

wörks.
