### ISSUE TITLE
re-loadout script

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/TvT_Dark_Business_Adleredition.altis#28]
for unknown reasons, initial loadout script partially  failed with 50 ppl. there should be a "give me my loadout" button somewhere for the first X minutes, so errors can be corrected, and less people get their loadouts all at once.
- [x] loadout done via a3g-loadout
- [x] re-add radios
- [ ] make sure it works with heavily loaded server

**Comment by nomisum** [comment]
didnt find anything in my RPT

had NVG and ARCO (alpha-1 FTL)

**Comment by Fusselwurm** [comment]
- for 15 minutes, a re-eqip action exists at arsenal 
- more complete adding/removal of loadout

**Comment by Fusselwurm** [comment]
blegh, what if a users uniform or vest is removed, but not re-added? i will need to get class names for default vdest/uniforms -.-

**Comment by Fusselwurm** [comment]
trying to use a3g-loadout in https://github.com/gruppe-adler/TvT_Dark_Business_Adleredition.altis/tree/28-refactor-loadout , but that has some  serious limitations: I need for example to base the loadout on the combination of SIDE and RANK - impossible with the simple side/class/unit name based config classes in a3g-loadout

**Comment by Fusselwurm** [comment]
hostage seems to hold microdagr (minor)

**Comment by Fusselwurm** [comment]
map light for all soldiers missing

**Comment by Fusselwurm** [comment]
fixed with 747a23b5f7d654188d09025f0cdc556dcc4e98bf and c61a46816708c271f4e6f3aa7b2e676b11d5a987
