### ISSUE TITLE
ensure JIP works for drop-outs

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/TvT_Dark_Business_Adleredition.altis#7]
- on/off switch for JIP (close/open the game)
- ideally, let people get into the same slot as before

**Comment by Fusselwurm** [comment]
> on/off switch for JIP (close/open the game)

It seems that's what `#lock` , `#unlock` is for

**Comment by nomisum** [comment]
nice. es gibt btw auch https://community.bistudio.com/wiki/didJIP

**Comment by nomisum** [comment]
test erfolgreich
